Add bookings
bannovdaniil/java-shareit pull request #2
Opened 2022-08-31 22:56 UTC by bannovdaniil

Идет выполнение согласно TDD и ТЗ

2022-09-02 18:09 UTC, eugene-lenkevich requested changes
Привет, Даниил, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-09-02 18:09 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/comment/model/Comment.java
> +    @ManyToOne(optional = false, fetch = FetchType.EAGER)
fetch = FetchType.EAGER

Это значение там вроде как по умолчанию, его можно не указывать :)

2022-09-02 18:09 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @Column(name = "description")
В данном случае наименование поля будет соответствовать наименованию колонки в таблице БД, можно лишнее не писать - не повторяться :)

2022-09-02 18:09 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        Optional<User> user = userRepository.findById(userId);
Это все можно покомпактнее записать, раз Optional используешь :)

User user = userRepository.findById(userId).orElseThrow(...);

2022-09-02 18:09 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private Long owner;
А не лучше ли поле так и назвать - ownerId, тогда будет понятно что это только идентификатор. Точно так же может быть объявлена связанная сущность и потому имя поля может быть неоднозначно :)

2022-09-02 20:26 UTC, bannovdaniil commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private Long owner;
в рекомендации к ТЗ были даны такие наименования, но т.к. меня это тоже напрягало исправил.

2022-09-03 03:11 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private Long owner;
Ох уж это ТЗ)

2022-09-03 03:12 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-09-03 14:33 UTC, merged