Add item requests
bannovdaniil/java-shareit pull request #3
Opened 2022-09-14 17:34 UTC by bannovdaniil

Добавление нового функционала согласно ТЗ
и тестирование.

2022-09-19 05:43 UTC, eugene-lenkevich requested changes
Привет, Даниил, спасибо за PR

В целом все супер, но есть пара моментов на счет использования JPA, посмотри комментарии пожалуйста :)

2022-09-19 05:43 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByItemUserIdAndItemIdOrderByStartDesc(Pageable pageable, Long userId, Long itemId, LocalDateTime dateTime);
1. Если мы используем @query то уже не обязательно писать такие длинные имена методов :)
2. Не уверен что нужен join в этом запросе, можно же напрямую проверять b.itemId на соответствие параметру 
3. ORDER BY b.start DESC.  У нас же в метод передается объект Pageable, в нем есть возможность задать сортировку, руками в запросе писать сортировку избыточно и, предположу, что в некоторых случаях еще и падать будет на неверном синтаксисе sql :)

Это касается наверно всех методом в этом классе, везде можно по этим пунктам проверить :)

И, кстати, 'SELECT b' можно не писать 
 @Query("from Booking as b ...")

2022-09-19 05:43 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByItemOwnerAndEndIsBeforeOrderByStartDesc(Pageable pageable, Long ownerId, LocalDateTime dateTime);
И что то мне подсказывает что оставив название метода вот таким

findAllByItemOwnerAndEndIsBefore(...)

он будет работать и без указания руками Query :)
Опять таки, все сортировки задавать можно через Pageable

https://habr.com/ru/post/435114/

B вот, кстати, такая шпаргалочка 
https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#repository-query-keywords

PS: а в других репозиториях все гут.... )

2022-09-19 05:43 UTC, eugene-lenkevich commented on src/test/java/ru/practicum/shareit/user/repository/UserRepositoryTest.java
> +        userRepository.deleteAll();
Вроде как и так в БД ничего не сохранится, сверху стоит Transactional, по идее после каждого теста транзакция откатывается, можешь проверить если интересно :)

2022-09-19 05:43 UTC, eugene-lenkevich commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    private UserService userService;
Кстати, очень правильно сделать мок на сервис. Этот тест проверяет работу web-слоя, если бы был сделан мок на репозиторий, то при падении сервиса у нас бы падал и этот тест, что не очень хорошо для диагностики :)

2022-09-19 14:42 UTC, bannovdaniil commented on src/test/java/ru/practicum/shareit/user/repository/UserRepositoryTest.java
> +        userRepository.deleteAll();
внес изменения, Transactional, при IDENTITY генерации ключей не сильно помогает. Данные сбрасывает, а счетчик с ID продолжает крутить :) а deleteAll() как наставник показал :)

все почистил.

2022-09-19 16:35 UTC, bannovdaniil commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByItemUserIdAndItemIdOrderByStartDesc(Pageable pageable, Long userId, Long itemId, LocalDateTime dateTime);
про "SELECT b" это интересно, если где встречу не буду удивляться, но мне так привычнее, на SQL больше похоже.

2022-09-19 17:03 UTC, bannovdaniil commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByItemOwnerAndEndIsBeforeOrderByStartDesc(Pageable pageable, Long ownerId, LocalDateTime dateTime);
не заработало, на всякий случай проверил, ItemOwner это значение поля берется из другой таблицы, которая по JOIN подцепляется.
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-09-19 20:01:54.299 ERROR 10020 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bookingController' defined in file [C:\work\PraktikumJava\java-shareit\target\classes\ru\practicum\shareit\booking\BookingController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bookingServiceImpl' defined in file [C:\work\PraktikumJava\java-shareit\target\classes\ru\practicum\shareit\booking\service\BookingServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bookingRepository' defined in ru.practicum.shareit.booking.repository.BookingRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Invocation of init method failed; nested exception is org.springframework.data.repository.query.QueryCreationException: Could not create query for public abstract java.util.List ru.practicum.shareit.booking.repository.BookingRepository.findAllByItemOwnerAndEndIsBefore(org.springframework.data.domain.Pageable,java.lang.Long,java.time.LocalDateTime); Reason: Failed to create query for method public abstract java.util.List ru.practicum.shareit.booking.repository.BookingRepository.findAllByItemOwnerAndEndIsBefore(org.springframework.data.domain.Pageable,java.lang.Long,java.time.LocalDateTime)! No property 'itemOwner' found for type 'Booking'; nested exception is java.lang.IllegalArgumentException: Failed to create query for method public abstract java.util.List ru.practicum.shareit.booking.repository.BookingRepository.findAllByItemOwnerAndEndIsBefore(org.springframework.data.domain.Pageable,java.lang.Long,java.time.LocalDateTime)! No property 'itemOwner' found for type 'Booking'

```
в

2022-09-19 17:05 UTC, bannovdaniil commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByItemOwnerAndEndIsBeforeOrderByStartDesc(Pageable pageable, Long ownerId, LocalDateTime dateTime);
за статьи спасибо ознакомился.

2022-09-19 17:10 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByItemOwnerAndEndIsBeforeOrderByStartDesc(Pageable pageable, Long ownerId, LocalDateTime dateTime);
> не заработало, на всякий случай проверил, ItemOwner это значение поля берется из другой таблицы, которая по JOIN подцепляется.
> 
> ```
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 2022-09-19 20:01:54.299 ERROR 10020 --- [           main] o.s.boot.SpringApplication               : Application run failed
> 
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bookingController' defined in file [C:\work\PraktikumJava\java-shareit\target\classes\ru\practicum\shareit\booking\BookingController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bookingServiceImpl' defined in file [C:\work\PraktikumJava\java-shareit\target\classes\ru\practicum\shareit\booking\service\BookingServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bookingRepository' defined in ru.practicum.shareit.booking.repository.BookingRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Invocation of init method failed; nested exception is org.springframework.data.repository.query.QueryCreationException: Could not create query for public abstract java.util.List ru.practicum.shareit.booking.repository.BookingRepository.findAllByItemOwnerAndEndIsBefore(org.springframework.data.domain.Pageable,java.lang.Long,java.time.LocalDateTime); Reason: Failed to create query for method public abstract java.util.List ru.practicum.shareit.booking.repository.BookingRepository.findAllByItemOwnerAndEndIsBefore(org.springframework.data.domain.Pageable,java.lang.Long,java.time.LocalDateTime)! No property 'itemOwner' found for type 'Booking'; nested exception is java.lang.IllegalArgumentException: Failed to create query for method public abstract java.util.List ru.practicum.shareit.booking.repository.BookingRepository.findAllByItemOwnerAndEndIsBefore(org.springframework.data.domain.Pageable,java.lang.Long,java.time.LocalDateTime)! No property 'itemOwner' found for type 'Booking'
> ```
> 
> в

Поле сущности называется itemId, а тут itemOwner, на что и ругается что нет такого поля :)
![image](https://user-images.githubusercontent.com/94845100/191074170-433fcd2b-73d6-4fa3-b575-42dc78d39d5c.png)

2022-09-19 17:10 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByItemOwnerAndEndIsBeforeOrderByStartDesc(Pageable pageable, Long ownerId, LocalDateTime dateTime);
А, пардон, речь же про bookerId, но суть та же

2022-09-20 04:49 UTC, eugene-lenkevich approved these changes
Ок, спасибо!

2022-09-21 11:14 UTC, merged