Add docker
bannovdaniil/java-shareit pull request #4
Opened 2022-09-25 18:10 UTC by bannovdaniil

Разбивка на микро сервисы.

2022-09-28 05:34 UTC, eugene-lenkevich requested changes
Привет, Даниил, спасибо за PR

В целом все супер, докер, два сервиса, все на месте :)

Я оставил пару комментариев на счет структуры, главное разобраться с контрактами. Если будут вопросы - спрашивай :)

2022-09-28 05:34 UTC, eugene-lenkevich commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +public class BookItemRequestDto {
Мне кажнтся или одни и те же dto находятся и в гейтвее и в сервере, наверное это не очень хорошо. 
В будущем, придеться вносить изменения в два разных места и, рано или поздно, это приведет к рассинхронизации реализаций и появлению множества багов просто из-за несоотвествия контрактов сервисов. А в микросервисах починка багов - это то еще приключение :)

Иногда вообще как делают. Микросервис разбивают на два модуля: реализация и контракты (все dto и пр интерфейсы). Другой микросервис (в нашем случае это gateway), который хочет обратится к нашему сервису, импортирует наши контракты и с помощью них и строит запросы. Так обеспечивается соответствие API.
В контракты так же может быть помещен и web-клиент со всем настройками, соответственно, импортируем контракты, инжектим бин клиента, вызываем методы клиента, все остальное от нас сокрыто, не надо возится с настройками и API, в теории, всегда у нас соответствует :)

Тут возможно несколько вариантов, можно сделать зависимость на гейтвей (где и будут наши модули) или вынести все контракты в отдельный модуль. Есть над чем подумать, главное чтоюы не было валидации dto в сервере, так в ТЗ просят :)

2022-09-28 05:34 UTC, eugene-lenkevich commented on gateway/src/main/java/ru/practicum/shareit/user/UserClient.java
> +                builder
Этот код, инициализация билдера, повторяется в нескольких местах, можно его перенести в базовый класс, но это половинчатое решение.

Хочу обратить внимание на то, что в самом сервисе происходит и его инициализация, это не очень правильно архитектурно, инициализацию мы можем вынести вовне, убрав тем самым с сервиса дополнительную обязанность. Делается это вот как: в спринге можно описывать бины с помощью аннотаций(@Service, @Component и тп), а можно с помощью файлов конфигурации. Вот у меня есть такой пример

![image](https://user-images.githubusercontent.com/94845100/192694457-2e1efd0a-4492-4e3c-850b-f936c0dc4f05.png)

Можешь попробовать. Аннотацию @Service только надо будет убрать, а в остальном все то же самое :) 

PS есть еще вариант с описанием бинов в XML, но это устаревший способ 

Вот тут есть примерчики
https://spring-projects.ru/guides/lessons/lesson-2/

![image](https://user-images.githubusercontent.com/94845100/192695241-31a9d14a-2760-4be1-816c-dfa940f0c15d.png)

2022-09-28 18:59 UTC, bannovdaniil commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +public class BookItemRequestDto {
не совсем понял задачу, тоесть надо завести еще один микросервис который будет хранилищем DTO в серелизованном виде и к нему будут все остальные обращаться и получать свежие версии DTO?
 Сама идея конечно же интересная, но по времени реализации можно утонуть, а учебный проект этого не стоит. Почитал на эту тему в интернетах, про обмен DTO между микросервисами.
  Вроде как это не есть хорошо. 

> My advice? Do not share these DTOs among the applications in any kind of library. Or at least don't do this right now.
> I know, seems very counter-intuitive. You are duplicating code, right? But this is not a business rule, so you can be more flexible.
> The service that sends the DTO needs to be rigid in his message contract, like an Rest API. The service can't change the DTO in a way that could break the other services that are already consuming the information from the DTO.
> When a new field is added do DTO, you only update the other services that consume this DTO if they need the new field. Otherwise, forget it. Using JSON as content-type you have the flexibility to create and send new attributes without breaks the code of the services that don't map these new fields on his actual versions of DTO.
> But if this situation is really bothering you, you can follow the [Rule of Three](https://blog.codinghorror.com/the-delusion-of-reuse/):
>     There are two "Rules of Three" in reuse: (a) It is three times as difficult to build reusable components as single use components, and (b) a reusable component should be tried out in three different applications before it will be sufficiently general to accept into a reuse library.
> So, try to wait a bit more before sharing this DTO among the services.

2022-09-28 22:35 UTC, bannovdaniil commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +public class BookItemRequestDto {
Вынес DTO в отдельный модуль Maven не уверен на сколько это верно, но других мыслей кроме серилизации, нет.

2022-09-28 22:36 UTC, bannovdaniil commented on gateway/src/main/java/ru/practicum/shareit/user/UserClient.java
> +                builder
сделал в меру моих познаний спринга, параметризованный Bean через builder не получилось, сделал обычный.

2022-09-29 06:03 UTC, eugene-lenkevich commented on gateway/src/main/java/ru/practicum/shareit/user/UserClient.java
> +                builder
А почему бы и нет, пусть будет так, в принципе и так тоже можно, в итоге настройка клиента и сам клиент разнесены :)

2022-09-29 06:25 UTC, eugene-lenkevich commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +public class BookItemRequestDto {
Шикарный вопрос!

Все абсолютно верно, шарить dto и сущности между сервисами не хорошо - так получается распределенный монолит. 
У разных сервсов может быть разная доменная модель. Предположим у нас есть автосалон, в нем есть отдел продаж, автосервис, трейд-ин, и пусть будет еще страховой/ипотечный отдел. Везде у нас сущность она и та же - автомобиль, но в каждом отделе это разная сущность,  требуется разный набор полей. И иметь единую сущность в каждом из серисов, то есть модель со всеми возможными полями, явно избыточно (уровень масла в кредитном отделе никого не интересует как и наоборот), но, при изменении модели мы обязаны будем обновлять все сервисы (недостаток монолита) плюс получаем весь тот геморой с распределенным взаимодействием микросервисов (недстаток микросервисов). То есть мы получаем все самое хреновое из обоих парадигм одновременно )))

Но, тут идея была не в том чтобы сделать общую модель, а в  том чтобы разделить сервис (server в данном случае) на две части: сам сервис и его контракты (dto и интерфейсы). И это не отдельный микросервис, это просто мавеновские модули. 

Например, модули могут быть такими
gateway
server
 -- server-api
 -- server-src

И, соответственно, gateway имеет зависимость на server-api, импортирует оттуда все dto и интерфейсы, но, это не расшаренная доменная модель, это просто интерфейс взаимодействия с другим сервисом. Один сервис обращается в другой через эти интерфейсы, получает данные и перекладывает то, что ему нужно в вою доменную модель. То есть доменную модель они не разделяют, она везде своя.
 
В принципе то что ты сделал это оно и есть, достаточно в рамках этого задания. Но важно этот момент все же проговорить: вроде как и в первом случае и во втором мы делаем одно и то же - подключаем модуль с dto, но концептуально подходы совершенно разные и на первый взгляд разницу можно и не уловить, но она критическая :)

https://www.vinsguru.com/microservices-architecture-how-to-share-dto-data-transfer-objects/

2022-09-29 06:27 UTC, eugene-lenkevich approved these changes
Отличное задание, вроде не сильно сложное но про архитектуру :)
Спасибо!

2022-09-29 16:44 UTC, merged